config/routes.rb
Rails.application.routes.draw do
  resources :reports
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  namespace :api do
    namespace :v1 do
      resources :users 
      post "login", to: "users#login"
      resources :reports
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/news.rb
class News < ApplicationRecord
  has_one :news_type  
end

app/models/news_type.rb
class NewsType < ApplicationRecord
  belongs_to :news
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  belongs_to :role
  has_many :reports
  validates_uniqueness_of :email

  
  include BCrypt

  def password
    @password ||= Password.new(password_digest)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_digest = @password
  end
  
    def new_attribute 
      {
        id: self.id,
        email: self.email,
        name: self.name,
        role_name: self.role.name
      }
    end
end

app/controllers/api/v1/reports_controller.rb
module Api
  module V1
    class ReportsController < ApplicationController
      before_action :authorize, only: [:show, :update, :destroy]
      # GET /reports or /reports.json
      def index
        @reports = Report.all
        render json: @reports
      end

      def create
        @report = Report.new(report_params)
        if @report.save
          render json: @report, status: :ok
        else
          render json: {"message": @report.errors}, status: :unprocessable_entity
        end
      end

      def show
        @report = Report.where(:user_id => @user.id)
        render json: @report
      rescue ActiveRecord::RecordNotFound => e
        render json: {
          error: e.to_s
          }, status: :not_found
      end

      def update
        if @report.update(report_params)
          render json: @report
        else
          render json: @report.errors, status: :bad_request
        end
      end


      private
      
      def report_params
        params.require(:report).permit(:report_content, :date, :user_id)
      end

    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      before_action :authorize, only: [:show, :update, :destroy]
      def index
        @users = User.all
        render json: @users
      end

      def create
        @user = User.new(user_params)
        @user.password = user_params[:password_digest]
        token = encode_token({user_id: @user.id})
        if @user.save
          render json: {user: @user.new_attribute, token: token}
        else
          render json: {"message": @user.errors}, status: :bad_request
        end
      end

      def show
        @user = User.find_by_id(@user.id)
        render json: @user
      rescue ActiveRecord::RecordNotFound => e
        render json: {
          error: e.to_s
          }, status: :not_found
      end

      def update
        if @user.update(user_params)
          render json: @user.new_attribute
        else
          render json: @user.errors, status: :bad_request
        end
      end

      def destroy
        @user = User.find_by_id(params[:id])
        if @user.present?
          @user.destroy
          return render json: @user
        else
          return render json: {error: 'User not found'}
        end
      end

      def login
        @user = User.find_by_email(params[:email])

        if @user && @user.password == params[:password]
          token = encode_token({id: @user.id, email: @user.email})
          render json: {user: @user.new_attribute, token: token}
        else
          render json: {error: 'Invalid email or password'}, status: :unprocessable_entity
        end
      end
        

      private
      
      def user_params
        params.require(:user).permit(:name, :email, :gender, :ktp, :password_digest, :role_id)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  def encode_token(payload,exp=1.days.from_now)
    payload[:exp] = exp.to_i
    JWT.encode(payload, 'secret')
  end

  def decoded_token
    #auth bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjpudWxsfQ.usUC8ObZll751xV7FqJJgL6jemaYjKz8Ll5exP34rPw

    auth_header = request.headers['Authorization']

    if auth_header
      token = auth_header.split(' ')[1]
      begin
        JWT.decode(token, 'secret', true, algorithm: 'HS256')
      rescue JWT::DecodeError
        nil
      end
    end
  end

  def authorized_user
    decoded_token = decoded_token()
    if decoded_token
      email = decoded_token[0]['email']
      @user = User.find_by_email(email)
    end
  end

  def authorize
    render json: {message: 'You have to log in'}, status: :unauthorized unless 
    authorized_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocalGovermentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_with(model: report) do |form| %>
  <% if report.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/_report.html.erb
<div id="<%= dom_id report %>">
</div>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Show this report", @report %> |
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reports</h1>

<div id="reports">
  <% @reports.each do |report| %>
    <%= render report %>
    <p>
      <%= link_to "Show this report", report %>
    </p>
  <% end %>
</div>

<%= link_to "New report", new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render "form", report: @report %>

<br>

<div>
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @report %>

<div>
  <%= link_to "Edit this report", edit_report_path(@report) %> |
  <%= link_to "Back to reports", reports_path %>

  <%= button_to "Destroy this report", @report, method: :delete %>
</div>